# Place in .github/workflows/triage-scheduled-tasks.yml
name: Triage Scheduled Tasks
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '5 * * * *'   # Hourly — no-response close + PR requirements check
    - cron: '30 1 * * *'  # Daily at 1:30 AM UTC — stale issues

jobs:
  no-response:
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-no-response-close.yml@main
    permissions:
      issues: write

  pr-requirements:
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-pr-requirements.yml@main
    permissions:
      issues: read
      pull-requests: write

  stale:
    if: github.event.schedule == '30 1 * * *'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-stale-issues.yml@main
    permissions:
      issues: write
