# Place in .github/workflows/triage-issues.yml
name: Issue Triaging
on:
  issues:
    types: [opened, reopened, labeled, unlabeled, closed]
  issue_comment:
    types: [created]

jobs:
  label-incoming:
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'unlabeled'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-label-incoming.yml@main
    permissions:
      issues: write

  close-invalid:
    if: github.event.action == 'labeled'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-close-invalid.yml@main
    permissions:
      contents: read
      issues: write
      pull-requests: write

  close-single-word:
    if: github.event.action == 'opened'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-close-single-word-issues.yml@main
    permissions:
      issues: write

  close-off-topic:
    if: github.event.action == 'labeled'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-close-off-topic.yml@main
    permissions:
      issues: write

  feature-request-comment:
    if: github.event.action == 'labeled'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-feature-request-comment.yml@main
    permissions:
      issues: write

  unable-to-reproduce:
    if: github.event.action == 'labeled'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-unable-to-reproduce-comment.yml@main
    # with:
    #   log_menu_path: '`Help` > `Show Logs in Finder/Explorer`'
    permissions:
      issues: write

  remove-triage-label:
    if: github.event.action == 'labeled'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-remove-label-on-reply.yml@main
    permissions:
      issues: write

  on-issue-close:
    if: github.event.action == 'closed'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-on-issue-close.yml@main
    permissions:
      issues: write

  no-response:
    if: github.event_name == 'issue_comment'
    uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-no-response-close.yml@main
    permissions:
      issues: write

  # discuss:
  #   if: github.event.action == 'labeled'
  #   uses: desktop/gh-cli-and-desktop-shared-workflows/.github/workflows/triage-discuss.yml@main
  #   with:
  #     target_repo: 'your-org/your-internal-repo'
  #     cc_team: '@your-org/your-team'
  #   secrets:
  #     discussion_token: ${{ secrets.DISCUSSION_TRIAGE_TOKEN }}
